
all:
	$(MAKE) -C test-interactive
	$(MAKE) -C test-parser
	$(MAKE) -C test-tcp
	$(MAKE) -C test-tcp-srq
	$(MAKE) -C test-hmm


clean:
	$(MAKE) clean -C test-interactive
	$(MAKE) clean -C test-parser
	$(MAKE) clean -C test-tcp
	$(MAKE) clean -C test-tcp-srq
	$(MAKE) clean -C test-hmm


